### PR TITLE
[enh] Autocompletion, init script and other CLI enhancements

### PR DESCRIPTION
**Pull request by Kloadut**
PR in progress, need tests

### CODE REVIEW

**Comment by frankrousseau** [comment]
Could you run a PEP8 validation on your files? I use a plugin in vim for that, but I think there is a CLI too.

**Comment by Kloadut** [comment]
Done as of bc7769e

**Comment by Kloadut** [comment]
BTW, is it possible to rename the repo to "cozy-fuse", since it does not really concern Linux ?
Also because I will push this to pypi really soon

**Comment by frankrousseau** [comment]
Done for the renaming. Is the PR good to merge?

**Comment by Kloadut** [comment]
I'll just update the setup.py and setup.cfg

**Comment by Kloadut** [comment]
@frankrousseau Ready for the merge :)

**Comment by frankrousseau** [comment]
Could you advertise it on the forum by announcing it as an alpha version?

**Comment by Kloadut** [comment]
Ok, let me push it to pypi before

**Pull request merged**
